version: '3.7'
services:
    postgres:
        image: postgres:9.6
        container_name: Postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        logging:
            options:
                max-size: 10m
                max-file: "3"
    mysql:
        image: mysql:5.7
        platform: linux/amd64
        container_name: Mysql
        ports:
            - 3306:3306    
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
        volumes:
            - ./mysql_data/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
            - ./op_files:/var/lib/mysql-files/
            # Production Environments Setup
            #- ./mysql.cnf:/etc/mysql/mysql.cnf
            #- ./schemas:/var/lib/mysql
    webserver:
        image: puckel/docker-airflow:1.10.9
        container_name: Airflow
        restart: always
        depends_on:
            - postgres
            - mysql
        environment:
            - INSTALL_MYSQL=y
            - LOAD_EX=n
            - EXECUTOR=Local
            - AIRFLOW__SMTP__SMTP_HOST=${SMTP_HOST}
            - AIRFLOW__SMTP__SMTP_USER=${EMAIL}
            - AIRFLOW__SMTP__SMTP_PASS=${EMAIL_PASS}
            - AIRFLOW__SMTP__SMTP_PORT=587
            - AIRFLOW__SMTP__SMTP_MAIL_FROM=${SMTP_MAIL_FROM}
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./ip_files:/usr/local/airflow/ip_files
            - ./op_files:/usr/local/airflow/op_files
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
